export type FeaturePage = {
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  headline: string;
  subheadline: string;
  icon: string;
  keyBenefits: string[];
  comparisonPoint: string;
  faqItems: { q: string; a: string }[];
};

export const FEATURE_PAGES: FeaturePage[] = [
  {
    slug: "auto-repair-invoices",
    title: "Auto Repair Invoice Software",
    metaTitle: "Auto Repair Invoice Software for Mobile Mechanics | DriveSync",
    metaDescription:
      "Generate professional, state-compliant auto repair invoices in seconds. DriveSync beats ARI on mobile speed, Stripe payments, and zero per-transaction fees.",
    headline: "Invoices That Close Jobs Faster",
    subheadline:
      "Create, send, and collect on professional auto repair invoices from a customer's driveway — not back at your desk.",
    icon: "🧾",
    keyBenefits: [
      "Generate a signed invoice in under 60 seconds",
      "Accept card, BNPL (Affirm/Klarna), or cash on-site",
      "Auto-attach labor, parts, tax, and environmental fees",
      "Send via native SMS — no app install required for customer",
      "QuickBooks sync on payment",
      "California BAR-compliant formatting built-in",
    ],
    comparisonPoint:
      "ARI requires desktop access to finalize invoices. DriveSync is built for the driveway.",
    faqItems: [
      {
        q: "Is DriveSync's invoice software compliant with California BAR regulations?",
        a: "Yes. Every invoice generated by DriveSync includes all fields mandated by the California Bureau of Automotive Repair, including authorization signatures, parts itemization, and labor descriptions.",
      },
      {
        q: "Can I accept card payments directly on the invoice?",
        a: "Yes. DriveSync embeds a Stripe-powered payment link in every invoice. Customers can pay by card, Apple Pay, or BNPL — no separate terminal needed.",
      },
      {
        q: "Does DriveSync charge per-invoice fees?",
        a: "No. DriveSync charges a flat monthly subscription. You keep 100% of your revenue minus Stripe's standard processing fees.",
      },
    ],
  },
  {
    slug: "vehicle-inspections",
    title: "Digital Vehicle Inspection Software",
    metaTitle:
      "Digital Vehicle Inspection Software for Mobile Mechanics | DriveSync",
    metaDescription:
      "Perform multi-point vehicle inspections with photo evidence, pre-existing damage waivers, and instant customer sign-off. Built for mobile mechanics.",
    headline: "Inspect. Document. Get Signed. In Minutes.",
    subheadline:
      "Replace paper inspection forms with a digital multi-point inspection that attaches photos, flags pre-existing damage, and gets customer authorization via SMS.",
    icon: "🔍",
    keyBenefits: [
      "Multi-point inspection checklist built into every work order",
      "Photo documentation for pre-existing damage protection",
      "Customer pre-authorization via SMS deep-link",
      "Automatic damage waiver generation",
      "Inspection history linked to vehicle VIN",
      "QA approval queue for multi-tech shops",
    ],
    comparisonPoint:
      "ARI inspection forms are static PDFs. DriveSync creates a live, signed, time-stamped digital record.",
    faqItems: [
      {
        q: "Can I take photos during an inspection and attach them to the work order?",
        a: "Yes. DriveSync's camera integration lets you capture and attach photos directly to any inspection point, creating a timestamped, court-admissible record.",
      },
      {
        q: "How does customer pre-authorization work?",
        a: "DriveSync sends the customer an SMS with a secure link. They review the inspection, sign digitally, and the authorization is logged to the work order — all before you turn a wrench.",
      },
      {
        q: "What happens if a customer disputes pre-existing damage?",
        a: "Your DriveSync inspection record includes timestamped photos, GPS coordinates, and a customer signature, providing clear documentation to resolve disputes.",
      },
    ],
  },
  {
    slug: "job-cards",
    title: "Digital Job Card Software for Mobile Mechanics",
    metaTitle: "Digital Job Cards for Mobile Mechanics | DriveSync",
    metaDescription:
      "Replace paper job cards with digital work orders that track labor, parts, status, and customer approvals — synced across your whole team in real time.",
    headline: "Your Paper Job Cards Are Costing You Money.",
    subheadline:
      "DriveSync digital job cards track every job from intake to payment, with real-time status updates, parts tracking, and change-order approval flows.",
    icon: "📋",
    keyBenefits: [
      "Create a job card from a VIN scan in under 30 seconds",
      "Track INTAKE → ACTIVE → INVOICED → PAID status in real time",
      "Change-order workflow with customer approval via SMS",
      "Attach labor lines, parts, and diagnostic fees",
      "Assign jobs to specific technicians (Multi-Van plan)",
      "Offline-capable — syncs when connection returns",
    ],
    comparisonPoint:
      "ARI job cards don't support SMS-based change order approvals. DriveSync closes the loop without a phone call.",
    faqItems: [
      {
        q: "Can my technicians update job cards from their phones?",
        a: "Yes. DriveSync is a mobile-first PWA. Techs can update job status, add labor notes, and upload photos directly from any smartphone — no app store install needed.",
      },
      {
        q: "How do change orders work?",
        a: "When additional work is discovered, you add a change order to the job card. DriveSync automatically sends the customer an SMS with a secure approval link. Work doesn't proceed until they sign.",
      },
      {
        q: "Does DriveSync work without an internet connection?",
        a: "Yes. DriveSync uses service workers to cache your active jobs. Updates sync automatically when your connection is restored.",
      },
    ],
  },
  {
    slug: "inventory-management",
    title: "Van Stock & Inventory Management for Mobile Mechanics",
    metaTitle: "Van Stock Inventory Management for Mobile Mechanics | DriveSync",
    metaDescription:
      "Track oil, filters, and consumables in your van with automatic stock deduction when a job is paid. Never run out of 5W-30 mid-job again.",
    headline: "Stop Running Out of Oil Mid-Job.",
    subheadline:
      "DriveSync tracks every quart of oil, every filter, and every consumable in your van. Stock auto-decrements when a job is paid — no manual counting.",
    icon: "🧴",
    keyBenefits: [
      "Track every consumable: oil, filters, brake cleaner, rags",
      "Set low-stock thresholds with red-glowing alerts",
      "Auto-deduct stock when a work order is marked PAID",
      "Cost-per-unit tracking for accurate job costing",
      "Multi-SKU inventory across your whole fleet",
      "Direct integration with the Global Lexicon for auto-lookup",
    ],
    comparisonPoint:
      "ARI requires manual inventory counts. DriveSync closes the loop automatically at payment.",
    faqItems: [
      {
        q: "How does automatic stock deduction work?",
        a: "When you mark a work order as PAID, DriveSync reads the vehicle's oil capacity from the Global Lexicon and automatically deducts the matching oil SKU from your inventory.",
      },
      {
        q: "Can I set low-stock alerts?",
        a: "Yes. Each inventory item has a configurable reorder threshold. When stock falls below it, the item glows red and appears in your low-stock alert banner.",
      },
      {
        q: "Does DriveSync track parts separately from consumables?",
        a: "Yes. Consumables (oil, rags, cleaner) are tracked in Van Stock. Parts used in a specific job are tracked on the work order with full cost-of-goods accounting.",
      },
    ],
  },
  {
    slug: "service-reminders",
    title: "Automated Service Reminder Software for Auto Repair",
    metaTitle: "Automated Service Reminders for Mobile Mechanics | DriveSync",
    metaDescription:
      "Send automated oil change and service reminders to past customers via SMS. DriveSync's AI-powered campaigns bring back 30% more repeat business.",
    headline: "Your Best Customers Forgot About You.",
    subheadline:
      "DriveSync automatically identifies customers who are due for service and sends personalized SMS reminders — without you lifting a finger.",
    icon: "⏰",
    keyBenefits: [
      "AI-generated, personalized reminder messages",
      "Trigger by mileage interval or time elapsed",
      "Native SMS delivery — no app required for customer",
      "Blast campaigns to your entire customer list",
      "Track reply rates and job bookings from campaigns",
      "TCPA-compliant opt-out handling",
    ],
    comparisonPoint:
      "ARI reminders are manual email blasts. DriveSync uses AI to personalize every SMS to the vehicle and service history.",
    faqItems: [
      {
        q: "How does DriveSync know when a customer is due for service?",
        a: "DriveSync tracks mileage and service dates from your work orders. When a customer's vehicle approaches the OEM-recommended service interval, it automatically queues a reminder.",
      },
      {
        q: "Are the reminder messages personalized?",
        a: "Yes. DriveSync uses AI to generate reminders that reference the customer's name, vehicle, and last service — making them feel like a personal call, not a mass marketing blast.",
      },
      {
        q: "How do I handle customers who don't want reminders?",
        a: "DriveSync includes TCPA-compliant opt-out management. Customers reply STOP and are immediately removed from all future campaigns.",
      },
    ],
  },
];
